// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF42SVEdSH6ZZsLz0hoAhBbD3Cj5WL0Es',
    appId: '1:34227350549:web:6e70dc851c622cc622f21c',
    messagingSenderId: '34227350549',
    projectId: 'flutter-firebase-test-ap-df3a4',
    authDomain: 'flutter-firebase-test-ap-df3a4.firebaseapp.com',
    storageBucket: 'flutter-firebase-test-ap-df3a4.appspot.com',
    measurementId: 'G-WT30THCT1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLcRw1Tm-jilOYEDKD3qQxeh3NTomZQMA',
    appId: '1:34227350549:android:91f6b654cee6ddb622f21c',
    messagingSenderId: '34227350549',
    projectId: 'flutter-firebase-test-ap-df3a4',
    storageBucket: 'flutter-firebase-test-ap-df3a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsSwBc4APrM-7WfGBfkJ6mgVeXyj1Cgbw',
    appId: '1:34227350549:ios:10c15d5e44e82a6022f21c',
    messagingSenderId: '34227350549',
    projectId: 'flutter-firebase-test-ap-df3a4',
    storageBucket: 'flutter-firebase-test-ap-df3a4.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsSwBc4APrM-7WfGBfkJ6mgVeXyj1Cgbw',
    appId: '1:34227350549:ios:c67a45e5ca3b6b5522f21c',
    messagingSenderId: '34227350549',
    projectId: 'flutter-firebase-test-ap-df3a4',
    storageBucket: 'flutter-firebase-test-ap-df3a4.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
